package com.leal.cipm_testing;

public class Defs {
    //hola alondra
    // fathers matter
    public String between = "una preposición usada para " +
            "decir que algo esta entre dos cosas.";
    public String children = "una palabra para referirse " +
            "a niños y niñas";
    public String ago = "se usa con una expresión de tiempo " +
            "para indicar que algo fue en pasado," +
            "por ejemplo = years ago- años atras, ten " +
            "years ago- hace diez años ";
    public String then = "entonces";
    public String iasked = "yo pregunté";
    public String which = "cual, usualmente la usamos cuando tenemos dos opciones";
    public String poses = "presentar o constituir(un problema, peligro,dificultad)";
    public String bigger = "mas grande(el sufijo ER se usa en " +
            "adjetivos cortos para hacer que comparen, " +
            "small/pequeño, smaller-mas pequeño," +
            " tall-alto,taller-mas alto)";
    public String threat = "amenaza";
    public String withouthmissingabeat = "esta es una exprecion coloquial, " +
            "es el equivalente en español a ¨sin titubear¨ ";
    public String hesaid = "el dijo";
    public String itwas = "fue";
    public String who = "quien";
    public String weall = "todos nosotros";
    public String know = "saber o conocer";
    public String that = "que (se usa para introducir una clausula)";
    public String growup = "verbo compuesto, crecer";
    public String likely = "propenso, probable";
    public String poverty = "pobreza";
    public String dropout = "salir de la escuela,dejar de ir a la escuela prematuramente";
    public String endup = "terminar";
    public String even = "incluso";
    public String after = "después , después de, después de que";
    public String controlling = "controlar, los verbos después " +
            "de cualquier preposición se escriben con terminación ing";
    public String varying = "algo que varia";
    public String householdincome = "ingreso del hogar";
    public String jail = "la carcel";
    public String mostlikely = "los mas probables/ superlativo ";
    public String windup = "terminar, encontrarte a ti mismo en una situacion inesperada y no placentera";
    public String eachother = "uno con el otro";
    public String risen = "participio de elevar, elevado";
    public String reached = "alcanzar en pasado, alcanzó";
    public String during = "durante";
    public String marriage = "matrimonio";
    public String were = "eran o estaban ";
    public String than = "que , se usa en contexto de comparacion";
    public String raised = "criado, en este contexto raise se usa como <criar> ";
    public String both = "ambos";
    public String written = "escrito";
    public String according = "según";
    public String outofwedlock = "fuera de matrimonio";
    public String birth = "nacimientos";
    public String lessthan = "menos de ";
    public String over = "sobre";
    public String answer = "respuesta";
    public String found = "Participio de find (encontrar) , encontrado";
    public String law = "ley";
    public String iff = "Conector condicional es el ´si´ en español,por ejemplo, si tu vienes yo voy";
    public String subsidize = "subsidiar";
    public String undesirable = "indeseable";
    public String behavior = "comportamiento";
    public String youwillget = "´will´ + get, juntos significan, tu obtendras. ´Will´ no tiene significado solo";

    public String soCalled = "así llamado, se usa para mostrar que algo o alguien se designa comúnmente " +
            "por el nombre o término especificado";
    public String war = "Guerra";
    public String began = "comenzó";
    public String begantoflatline = "comenzo alrededor";
    public String from = "desde";
    public String until = "hasta";
    public String untilnow = "hasta ahora";
    public String spent = "gastado, en esta situación esta justo después del has, has spent,ha gastado";
    public String hasspent = "ha gastado";
    public String tofightpoverty = "para luchar contra la pobreza";
    public String rate = "calificar";
    public String hasremainedunchanged = "se ha mantenido sin cambios";
    public String haschanged = "ha cambiado";
    public String dramatically = "dramáticamente";
    public String Thatsbecause = "Eso es porque";
    public String generous = "generoso";
    public String ineffect = "en efecto";
    public String abandon = "abandonar";
    public String traditional = "tradicional";
    public String financial = "financiero";
    public String responsibilities = "responsabilidades";
    public String suchdependency = "tal dependencia";
    public String learnedhelplessness = "Desamparo aprendido";
    public String disincentive = "desincentivo, especialmente una desventaja financiera, " +
            "que tiende a desalentar a las personas de hacer algo";
    public String tryingtohelp = "Tratando de ayudar";
    public String poor = "pobre";
    public String nonpoor = "no pobre";
    public String whether = "ya sea , expresar una duda o elección entre alternativas.";
    public String additional = "adicionales";
    public String respondents = "encuestados";
    public String oncesaid = "una vez dijo";
    public String headmitted = "él admitió";
    public String runningwith = "juntarse con";
    public String gangs = "pandillas";

    public String structure = "estructura";
    public String protection = "proteción";
    public String calmyoudown = "cálmarte";
    public String theway = "de la manera";
    public String teachyou = "enseñarte";
    public String howtobe = "a como ser";
    public String myrough = "muy áspero o muy fuerte de caracter";
    public String growingup = "creciendo";
    public String fulltimejobs = "trabajos de tiempo completo";
    public String asa = "como un";
    public String janitor = "conserje";
    public String also = "él también";
    public String hismid80s = "alrededor de sus 80 años";
    public String angry = "molesto";
    public String bitter = "amargado";
    public String insisted = "insistió";
    public String racialsegregation = "segregacion racial";
    public String yougetoutoflifewhatyouputintoit = "se refiere a = recibes lo que das";
    public String blamingotherpeople = "culpar a otras personas";
    public String whatcouldihavedonetochangetheoutcome = "que pude haber hecho yo para cambiar mi resultado";
    public String Thisadviceshaped = "este consejo formo";
    public String staffsergeant = "rango militar";
    public String jimcrowsouth = "leyes que segregaban a las personas de raza negra de la sociedad";
    public String fulltime = "de tiempo completo";
    public String somehow = "de alguna manera";
    public String cooked = "cocinaba";
    public String andsomehowmanaged = "y de alguna manera logró";
    public String nightschool = "escuela nocturna, una escuela que imparte clases por la noche, para " +
            "aquellos, generalmente adultos, que no pueden asistir durante el día";
    public String gethisGED = "obtener su diploma de estudios generales";
    public String heran = "que el administró";
    public String thelaterapper = "el fallecido rapero";
    public String fathersmatter = "los padres importan, o son importantes";
    public String wehave = "en esta situación , el we have, no es nosotros tenemos, como está al lado del until-(hasta o hasta que), el we have se hace " +
            "subjuntivo y realmente dice *hasta que nosotros tengamos ";


    //Is America Racist??
    public String Still = "todavía";
    public String Certainly = "ciertamente";
    public String Thinksso = "piensa de esta forma";
    public String That = "que";
    public String If = "sí, condicional";
    public String Doesntthatmean = "eso no siginfica?";
    public String So = "aquí el so se refiere a la acción anterior, “america ha cambiado y dramáticamente así";
    public String Vote = "votar";
    public String who2 = "quien";
    public String was = "fue";
    public String elected = "elegido";
    public String almost = "casi";
    public String later = "después";
    public String thats = "eso es";
    public String only = "solamente";
    public String themost = "el mas , superlative , no hay nada por encima";
    public String thereare = "hay , plural";
    public String take = "toma";
    public String marriage2 = "matrimonio";
    public String wrote = "escribió";
    public String viewed = "visto";
    public String benchmark = "marcador";
    public String stage = "escenario, en este caso se refiere al ultimo paso";
    public String were2 = "eran, fueron, estaban";
    public String until2 = "hasta";
    public String Galluppoll = "poll es encuesta Gallup es una empresa que se dedica a hacer encuestas , una encuesta de Gallup.";
    public String Found = "encontró";
    public String That2 = "aquí este that se refiere a “ese numero “ no es “que” por que no esta introduciendo una clausula completa.";
    public String Of = "de";
    public String All = "todos";
    public String By = "por";
    public String Rising = "elevándose";
    public String Whatabout = "expresión coloquial, como cuando tu dices “que hay sobre” o “que tal” y luego introduces una idea.";
    public String Racialprofiling = "es una idea, perfil racial, se refiere a que la gente es detenida por la policía solo por su color de piel.";
    public String Doesntthat = "eso no?";
    public String Remains = "sigue siendo";
    public String Summer = "Verano";
    public String Became = "se convirtio";
    public String Groundzero = "literal es donde sucedió un estallido atomico, pero se usa coloquialmente para indicar que fue el lugar que empezó un movimiento social."
            + "Shot- disparar en pasado";
    public String Unarmed = "desarmado";
    public String Teenager = "adolecente";
    public String While = "mientras";
    public String Cleared = "aquí se refiere a que “limpió” o “aclaró”";
    public String Wrongdoing = "se refiere a cualquier hecho con malicia , error o crimen";
    public String Citys = "aquí se refiere al “city´s pólice departmen” o el departamento de policía de la ciudad";
    public String Bias = "favoritismo o sesgo";
    public String Headlinegrabbingstat = "la primera palabra y sustantivo de esta frase es “stat” que es estadística headline es encabezado y grabbing viene de grab , ósea tomar con la mano, la frase completa es algo asi como la estadística que más agarro encabezados de periódico. A esto es a lo que le llamamos “noun adjective”";
    public String Gap = "hueco";
    public String Those = "aquellos";
    public String Notsofast = "no tan rapido";
    public String Coprise = "compone, contiene, esta compuesto por";
    public String Account = "cuantan por";
    public String Bigger = "mas grande";
    public String Even = "incluso";
    public String Than = "que";
    public String Pd = "pólice department";
    public String Cannot = "no puedes";
    public String About = "acerca de";
    public String Withouth = "sin";
    public String Though = "aun que";
    public String Commit = "cometer";
    public String Almost = "casi";
    public String Always = "siempre";
    public String Accordingto = "según";
    public String Bytheway = "por cierto";
    public String Over = "en esta situación “over” se refiere a sobre o mas de";
    public String Twice = "dos veces";
    public String Thatmany = "esta es una frase cuando están juntas , es como decir de esos";
    public String But = "pero";
    public String Same = "mismo";
    public String Mostly = "mayoritarimente";
    public String Unlike = "no parecido a";
    public String Dispatch = "parecido a “despachar” dispatch calls son cuando mandan a los policías aun lugar en especifico por una llamada de 911";
    public String Whenitcomesto = "frase colloquial parecida a = “cuando tiene que ver con”";
    public String Therefore = "por lo tanto";
    public String Haveafieldday = "“tienen un dia de campo” frase coloquial o “se dan gusto”";
    public String Actually = "realmente";
    public String Published = "publico";
    public String Called = "llamado";
    public String Outof = "aquí se refiere a que tres de cada cuatro, no aplica aquí su significado literal de las palabras aisladas";
    public String Drivers = "conductores";
    public String Were = "fueron";
    public String Average = "promedio";
    public String Likely = "probables";
    public String Speeding = "pasarse del limite de velocidad";
    public String Seatbelt = "cinturón de seguridad";
    public String Usage = "uso de";
    public String Lower = "mas bajo";
    public String Among = "entre";
    public String From = "de";
    public String Words = "palabras";
    public String Becauseof = "cuando las palabras estas están juntas son -  a razón de, o por";
    public String Also = "también";
    public String Higher = "mas alto";
    public String Rates = "tasa";
    public String Whether = "ya sea";
    public String Wearing = "usar, se usa para ropa, aquí se usa para el cinturón de seguridad";
    public String Safety = "seguridad";
    public String Thereis = "hay, singular";
    public String Theleast = "el menos";
    public String Better = "mejor";
    public String Any = "cualquier";
    public String Greater = "mas grande";

    //Don't Compare Yourself to Others

    public String Doyoueverlook = "Alguna vez miras";
    public String Iwish = "Yo deseo";
    public String Everybody = "Todos";
    public String Bet = "Apostar";
    public String Compared = "Comparado (del verbo comparar)";
    public String Yourself = "A ti mismo (Reflexivo)";
    public String Do = "Palabra usada para poner énfasis al afirmar algo. Ejemplo = No necesito esto, pero SI necesito aquello.";
    public String Own = "Propio";
    public String Middle = "Mitad";
    public String Asbigas = "Tan grande como";//10
    public String Pretty = "Muy. También usado como bonito (a) en otros contextos.";
    public String Hereswhy = "Aqua esta porque";
    public String People = "Personas ( en plural)";
    public String Whole = "Todo o completo";
    public String Trick = "Truco";
    public String HereswhatImean = "Aquí esta a lo que me refiero";
    public String Happiness = "Felicidad";
    public String Werebased = "Fuera basada";
    public String Biggest = "el mas grande";//20
    public String Business = "Negocio";
    public String Idbemad = "Contraccion de I would. Yo estaría muy enojado";
    public String Whoever = "Quien";
    public String Hebeastme = "El me gana / El me vence";
    public String Rich = "Rico";
    public String Alot = "Mucho";
    public String Like = "Como ( usado para comparación ). También puede significar gustar";
    public String Therewere = "Hay ( En plural)";
    public String Richer = "Mas rico";
    public String Never = "Nunca";//30
    public String Measure = "Medida";
    public String Constitutes = "Constituye";
    public String Success = "Exito";
    public String Entertainment = "Entretenimiento";
    public String Allthrough = "A traves";
    public String Career = "Carrera ( universitaria )";
    public String Customers = "Clientes";
    public String Someday = "Algún dia";
    public String Youllbe = "Contraccion de You will. Tu seras/estaras";
    public String Successful = "Exitoso (a)";//40
    public String Topguy = "hombre/chico superior";
    public String Someone = "Alguien ";
    public String Theyre = "Contraccion de They are. Ellos son/estaran";
    public String Disease = "Enfermedad";
    public String Save = "Salvar/Guardar ";
    public String Justlike = "igual como, igual que";
    public String Lawyer = "Abogado (a)";
    public String Crazy = "Loco";
    public String Makingaliving = "Expression = Literal indica hacer una vida, en otras palabras ganarse la vida";
    public String Pursuing = "Del verbo Persue; Persiguiendo";//50
    public String Findingmeaning = "encontrando significado";
    public String What = "Usado como conector, lo que.";
    public String First = "Primero";
    public String Standup = "Standup de comedia o show de comedia";
    public String Nobody = "Nadie";
    public String Tunedoutcrowds = "Multitudes desconectadas, o multitudes que no ponen atención.";
    public String Before = "Antes";
    public String Jokes = "Chistes";
    public String Laughing = "Del verbo Laugh. Riendo";
    public String about = "Sobre de / Acerca de ";//60
    public String Soldouthouses = "Houses es casas, aqui se refiere a lugares donde se hacen standups. Lugares agotados.";
    public String Iwasntplaying = "Yo no estaba presentando. Play es usado como presentar. ";
    public String Bigpayday = "Grandes dias de pago.";
    public String Able = "Capaz";
    public String Their = "Posesion = Su (de ellos/ellas)";
    public String Dark = "Oscuro";
    public String Struggle = "Luchas";
    public String Envy = "Envidio";
    public String Wentalongwithit = "que vienen con ello";
    public String Factor = "Factorizas";//70
    public String Sortof = "Tipo de";
    public String Mixandmatchgame = "Es un juego donde mesa americano donde diferente fotos se juntan y se mezclan. El autor se refiere a esto para indicar como se agarra unas partes de una persona pero no lo otro, cuando se comparan.";
    public String World = "Mundo";
    public String Heresoneoflifeslittletruths = "Aquí hay una de las pequeñas verdades de la vida";
    public String Packagedeal = "Paquete completo";
    public String View = "Ver";
    public String Someoneelseslife = "La vida de alguien mas ";
    public String Cheating = "Trampa";
    public String Prettycool = "Muy chido.";
    public String Hangwithhim = "salir con el/ pasar el rato con el";//80
    public String Pain = "Dolor";
    public String Anybody = "Cualquiera";
    public String Really = "Muy";
    public String Awfulstuff = "Cosas terribles";
    public String Dealwith = "lidiar con";
    public String Battle = "batallar con";
    public String Deadrockstars = "Estrellas de rock muertas";
    public String Hard = "Dura";
    public String Faceit = "enfrentalo";
    public String Sellout = "Agotar";//90
    public String Biggestvenues = "lugares mas grandes (venues se refiere al lugar donde el se presenta)";
    public String PrimetimeTVshow = "Programa de televisión en horario de máxima audiencia";
    public String Viewers = "Espectadores";
    public String Half = "Mitad";
    public String Myself = "Mi mismo (a)";
    public String Imdoingokay = "Expression = Estoy bien, me esta yendo bien";
    public String Try = "Intentar";

    //Fix Yourself
    public String Blamingothers = "Culpando otros ( Blame = Culpar)";
    public String Wasteoftime = "Perdida de tiempo";
    public String That3 = "Eso";
    public String Learn = "Aprender";
    public String Anything = "Cualquier cosa";
    public String Grow = "Crecer";
    public String Mature = "Madurar";
    public String Thus = "Por lo tanto";
    public String Life = "Vida";
    public String Better1 = "Mejor";//10
    public String As = "Como (Usado para comparar = como profesor)";
    public String Thereare = "Hay";
    public String Attitudes = "Actitudes";
    public String Toward = "Hacia";
    public String Sorrows = "Penas";
    public String Those1 = "Aquellos";
    public String First1 = "Primer/ Primero (a)";
    public String World1 = "Mundo";
    public String Second = "Segundo";
    public String Differently = "Diferentemente";//20
    public String Couple = "Pareja";
    public String Onthebrink = "A punto / al borde";
    public String Theyre1 = "Contraccion = They are, Ellos son/estan";
    public String Hurt = "Heridos (as)";
    public String Angry = "Molestos (as) / Enojados (as)";
    public String Unhappy = "Infeliz";
    public String Bitter = "Amargado";
    public String Husband = "Esposo";
    public String Recalls = "Recuerda";
    public String Things = "Cosas";//30
    public String Wife = "Esposa";
    public String Reasons = "Razones";
    public String Nolongerlivewithher = "Ya no puede vivir con ella";
    public String Harried = "Acosada (o)";
    public String Disillusioned = "Desilusionada";
    public String All1 = "Todas (os)";
    public String Ways = "Maneras";
    public String Letherdown = "La decepciono";
    public String Each = "Cada quien";
    public String Changes = "Cambios";//40
    public String Prospects = "Prospectos";
    public String Grim = "Oscuro";
    public String Arent = "Contraccion = Are not, no son/estan";
    public String Youre = "Contraccion = You are, tu estas/eres";
    public String Cant = "Contraccion = Can not, no puedes (no poder)";
    public String Yourself1 = "Tu mismo";
    public String Courage = "Coraje, Valor";
    public String Easier = "Mas facil";
    public String Muchmore = "Mucho mas";
    public String Gratifying = "Gratificante";//50
    public String Basest = "Mas bajos";
    public String Desires = "Deseos";
    public String Someoneelse = "Alguien mas";
    public String Youthful = "Juvenil";
    public String Makingastatement = "Haciendo una declaración";
    public String Against = "En contra";
    public String Smashing = "Aplastando / Del verbo Smash";
    public String Storefront = "Fachada";
    public String Business1 = "Negocio";
    public String Otherthan = "Aparte de";//60
    public String Bring = "Traer";
    public String Harm = "Daño";
    public String Whohavenothingtodo = "Quien no tienen nada que ver";
    public String Guilt = "Culpa";
    public String Doubt = "Duda / incertidumbre";
    public String Shame = "Lastima";
    public String Inevitably = "Inevitablemente";
    public String Suppressed = "Suprimido (a)";
    public String Beliefs = "Creencias";
    public String Unchanged = "Sin alterar/cambiar";//70
    public String Foster = "Fomentar";
    public String Anger = "Enojo";
    public String Alienation = "Alienación";
    public String Play = "Obra (También usado como jugar en otros contextos)";
    public String Characters = "Personajes";
    public String Veryhardtime = "Tiempo muy didicil";
    public String Profound = "Profundo (a)";
    public String Unhappiness = "Infelicidad";
    public String Suffering = "Sufrimiento";
    public String Own1 = "Propia (o)";//80
    public String Fault = "Culpa";
    public String Takenaback = "Expression = Tomado(a)  por sorpresa";
    public String If1 = "Si (Condicional = Usados para expresar que algo depende de algo mas)";
    public String Herfault = "Su culpa (Her = indicando posesión de ella, su de ella)";
    public String Shes = "Contraccion = She is, Ella es/esta";
    public String Doomed = "Condenada (o)";
    public String Herself = "Ella misma";
    public String Seem = "Parecen";
    public String Consigned = "Consigando (a)";
    public String Fate = "Destino";//90
    public String Mostofus = "Mayoría de nosotros (as)";
    public String Chance = "Oportunidad";
    public String Questions = "Preguntas";
    public String Full = "Completa (o)";
    public String Advantage = "Ventaja";
    public String Answer = "Respuesta";
    public String Try1 = "Intenta (del verbo intentar)";
    public String Stopdoing = "Deja de hacer";
    public String Wrong = "Equivocado (a)";
    public String Waste = "Gastes / Pierdas";//100
    public String Inopportunequestioning  = "cuestionamiento inoportuno (a)";
    public String Without = "Sin";
    public String Enlightening = "Literal es aluzar, pero se refiere a darle luz a algo para que se entienda mejor";
    public String Deflect = "Desviar";
    public String Something = "Algo";
    public String Right = "Bueno ( Esta palabra tiene varios usos, pero indica bueno)";
    public String Payingattention = "Poner atención (Literal es pagar atención pero en español es poner atención.)";
    public String Showuplate = "Llegar tarde";
    public String Spend = "Gastar";
    public String Itsnotamatter = "No es un asunto/cuestion";//110
    public String Some = "Algunos/Algunas";
    public String Imposed = "Impuesta (o)";
    public String Whatcouldyouputright = "Literal es que podrías poner derecho/bien pero se refiere a ¿Que podrías arreglar?";
    public String Rightnow = "Ahora mismo";
    public String Gettoworkontime = "Llega a tiempo al trabajo, get to es usado como llegar";
    public String Diligently = "Diligentemente";
    public String Utilize = "Utilizar";
    public String Peaceful = "Tranquilo (a)";
    public String Productive = "Productivo";
    public String Desirable = "Deseable";//120
    public String Weeks = "Semanas";
    public String Months = "Meses";
    public String Attentive = "Atento (a)";
    public String Effort = "Esfuerzo";
    public String Yourmindwillclear = "Tu mente se aclarará";
    public String Less = "Menos";
    public String Path = "Camino";
    public String Infront = "Enfrente";
    public String Willshine = "Verbo shine es brillar, con will enfrente indica futuro, brillará";
    public String Brightly = "brillantemente";//130
    public String Gettingyourownway = "meterte en tu propio camino";
    public String Instead = "En lugar de";
    public String Troubletoyourself = "problemas a ti mismo";
    public String Society = "Sociedad";
    public String Suffer = "Sufrir";
    public String Thatsthepriceofbeingalive = "Ese es el precio de estar vivo";
    public String Maybe = "Alomejor";
    public String Enough = "Suficiente";
    public String Burden = "Carga";
    public String Inthatfashion = "Es un expression indicando = de esa manera";//140
    public String Nobly = "Noble";
    public String Purpose = "Proposito";
    public String Properway = "Forma/manera apropiada";
    public String Fix = "Arregla";
    public String Inthatmanner = "de esa manera";
    public String Atleast = "Al menos";
    public String Place = "Lugar";

    public String Delusion = "creencia que contradice la realidad";
    public String Discerning = "Perspicaz, exigente, selectivo";
    public String Supervisedcurfews = "toque de queda supervisado.";
    public String Intimate = "intimo/a.";
    public String Violated = "violado/a (en el sentido de haber sido objeto de una acción no deseada o no consentida).";
    public String Vulnerable = "vulnerable, frágil.";
    public String Confined = "limitado/a, republic Stringido/a.";
    public String Satisfying = "satisfactorio/a, gratificante.";
    public String Emotionally = "emocionalmente.";
    public String Psychologically = "psicológicamente.";
    public String Physically = "físicamente.";
    public String Spiritually = "espiritualmente.";
    public String Commonsense = "sentido común.";
    public String Agenda = "programa, plan, intención.";
    public String Sociology = "sociología.";
    public String Anthropology = "antropología.";
    public String Genderstudies = "estudios de género.";
    public String Spectrum = "espectro.";
    public String Internalfeelings = "sentimientos internos.";
    public String Toytrucks = "camiones de juguete.";
    public String Pinkandbluestereotype = "estereotipo de rosa y azul.";
    public String Reality = "realidad.";
    public String Collegeentertainment = "entretenimiento universitario.";
    public String Makingstuffup = "inventando cosas.";
    public String Pushinganagenda = "promoviendo una agenda.";
    public String Traditionally = "tradicionalmente.";
    public String Marriage = "matrimonio.";
    public String Experience = "experiencia.";
    public String Research = "investigación.";
    public String Associateprofessor = "profesor asociado.";
    public String Theology = "teología.";
    public String Philosophy = "filosofía.";
    public String Beachball = "pelota de playa.";
    public String Distinctnature = "naturaleza distinta.";
    public String Bodyparts = "partes del cuerpo.";
    public String Biology = "biología.";
    public String Hormones = "hormonas.";
    public String Expressemotions = "expresar emociones.";
    public String Needs = "necesidades.";
    public String Desires2 = "deseos.";
    public String Uninvitedtouch = "toque no deseado.";
    public String Leg = "pierna.";
    public String HollywoodReporter = "Reportero de Hollywood.";
    public String CoStar = "coprotagonista.";
    public String Actingout = "representando.";
    public String Commonsense2 = "sentido común.";
    public String Rememberthebeachball = "recuerda la pelota de playa.";

    //Don't Waste Your Time
    public String Date = "Tener citas.";
    public String Purpose2 = "Proposito.";
    public String Getmarried = "Casarse.";
    public String Toofast = "Muy rapido.";
    public String Uncomfortable = "Incomodo.";
    public String Hookup = "Iniciar una relación romántica o sexual con alguien.";
    public String Casualflings = "Iventuras casuales.";
    public String Havefun = "Divertirse.";
    public String Dontgetmewrong = "No me malinterpretes.";
    public String Deeper = "Mas profundo.";//10
    public String Happiness2 = "Felicidad.";
    public String Certainly2 = "Ciertamente.";
    public String Marriage2 = "Matrimonio.";
    public String Topic = "Tema.";
    public String Atleast2 = "Al menos, por lo menos.";
    public String Else = "Más.";
    public String Letsfaceit = "Seamos realistas / Encaremoslo.";
    public String Asfasasitgoes = "Hasta donde llegue.";
    public String Frankly = "Francamente.";
    public String Smart = "Inteligente.";//20
    public String Playout = "Reproducir.";
    public String Often = "Seguido.";
    public String Relationship = "Relacion.";
    public String Commitment = "Compromiso.";
    public String Infact = "De hecho.";
    public String Arise = "Surgir.";
    public String Whim = "Capricho.";
    public String Develop = "Desarrollar.";
    public String Tryout = "Prueba.";
    public String Less2 = "Menos.";//30
    public String Lack = "Falta de.";
    public String Afford = "Poder pagar.";
    public String Enterprise = "Empresa.";
    public String Entirely = "En su totalidad / Totalmente.";
    public String Build = "Construir.";
    public String Shared = "Compartido.";
    public String Beliefs2 = "Creencias.";
    public String Partner = "Pareja / Compañero.";
    public String Profound2 = "Profundo.";
    public String Understandings = "Entendimientos.";//40
    public String Cutcome = "Resultados.";
    public String Fool = "Engañar.";
    public String Thrilled = "Emocionarse.";
    public String Kombucha = "Bebida alcholica.";
    public String Getdownto = "Llegar a.";
    public String Overthelongrun = "A largo plazo.";
    public String Stuff = "Cosas.";
    public String Faith = "Fe.";
    public String Sooner = "Mas pronto.";
    public String Doubt2 = "Duda.";//50
    public String Stuck = "Atrapado.";
    public String Deadendrelationships = "Relaciones sin salida.";
    public String Articulate = "Articular / Expresar.";
    public String Crave = "Anhelar.";
    public String Healthier = "Mas sano.";
    public String Wealthier = "Mas rico.";
    public String Towards = "Hacia.";
    public String Wasteoftime2 = "Perdida de tiempo.";
    public String Between = "Entre.";
    public String Taketheplunge = "Que ha dado el paso / Que se ha casado.";//60
    public String Country = "País.";
    public String Citizen = "Ciudadano.";
    public String Thelatter = "El ultimo.";
    public String Expectations = "Expectativas.";
    public String Mean = "Significar.";
    public String Reluctant = "Reacios.";
    public String Sign = "Firmar.";
    public String Ruleofthumb = "Una regla no escrita que todos seguimos.";
    public String Thekindof = "El tipo de.";
    public String Career2 = "Carrera.";//70
    public String Getitright = "Hacerlo bien.";

    //How to Make Our Cities Safer
    public String Homicides =  "asesinatos";
    public String Constitutional =  "constitucional";
    public String Cohort =  "cohorte";
    public String Highfrequencyoffenders =  "delincuentes de alta frecuencia";
    public String Felons =  "delincuentes";
    public String Verticalprosecution =  "prosecución vertical";
    public String Legalerrors =  "errores legales";
    public String Hostile =  "hostil";
    public String Progressivepoliticians =  "políticos progresistas";
    public String Incarceration =  "encarcelamiento";
    public String Agecrimecurve =  "curva de edad-crimen";
    public String Circulation =  "circulación";
    public String Rocketscience =  "ciencia espacial";
    public String Streettested =  "probado en la calle";
    public String Crimehotspots =  "zonas calientes del crimen";
    public String Potentialkillers =  "asesinos potenciales";
    public String Potentialvictims =  "víctimas potenciales";
    public String Interrogates =  "interroga";
    public String Nonfatal =  "no mortal";
    public String Organizedretailtheftrings =  "anillos de robo organizado en el comercio minorista";
    public String Lawenforcementofficials =  "funcionarios encargados de hacer cumplir la ley";
    public String UnitedStatesSentencingCommission =  "Comisión de Sentencias de los Estados Unidos";
    public String Shatteringrecords =  "rompiendo récords";
    public String Resourceandtimeintensive =  "intensivo en recursos y tiempo";
    public String Trialstage =  "etapa del juicio";
    public String Blamingeachother =  "culparse mutuamente";
    public String Hostiletowardsoneanother =  "hostiles entre sí";
    public String Sentencingguidelines =  "directrices de sentencia";
    public String Violentcrimerates =  "tasas de delitos violentos";


    //How to End Systemic Racism
    public String Racism = "Racismo.";
    public String Deserve = "Merecer.";
    public String Exposed = "Expuesto / expuesta.";
    public String Sooner2 = "Mas pronto.";
    public String Just = "Justo.";
    public String Truth = "Verdad.";
    public String College = "Universidad.";
    public String Encouraged = "Motivado.";
    public String Many = "Algunos.";
    public String Government = "Gobierno.";//10
    public String Harder = "Mas dificil.";
    public String Businesses = "Empresas.";
    public String Museum = "Museo.";
    public String Hardwork = "Trabajo duro.";
    public String Major = "Principal.";
    public String Parties = "Partidos.";
    public String Obtaining = "Obtención.";
    public String Driverslicense = "Licencia de conducir.";
    public String Construct = "Constructo.";
    public String Guaranteeing = "Garantizando.";//20
    public String Essentialskill = "Habilidad esencial.";
    public String Failure = "Fracaso.";
    public String Allowed = "Permitido.";
    public String Promoted = "Promovido.";
    public String Thenextgrade = "El siguiente grado.";
    public String Council = "Consulado.";
    public String Demonize = "Demonizar.";
    public String Budget = "Presupuesto.";
    public String Murder = "Asesinato.";
    public String Skyrocket = "Se disparan / sube.";//30
    public String Prosecutorsrefuse = "Los fiscales se rehusar.";
    public String Prosecute = "Enjuiciar.";
    public String Hardenedcriminals = "Criminales endurecidos.";
    public String Instead2 = "En cambio.";
    public String Prey = "Aprovecharse de.";
    public String Lawabiding = "Seguidores de la ley.";
    public String Hardworkingcitizens = "Ciudadanos trabajadores.";
    public String Again = "De nuevo.";
    public String Few = "Pocos.";
    public String Commonplace = "Comun.";//40
    public String Oppressive = "Opresivo.";
    public String Patronizing = "Patronizante.";
    public String Environment = "Ambiente.";
    public String Prejudices = "Prejuicios.";
    public String Prejudgments = "Prejuicios.";
    public String Goal = "Meta.";
    public String Claiming = "Reclamando.";
    public String Instituting = "Instituyendo.";
    public String Policies = "Políticas.";
    public String Holdingback = "Contener / retener.";//50
    public String Systemicracism = "Racismo sistematico.";
    public String Movingforward = "Ir hacia delante.";
    public String Pluralistic = "Pluralista.";
    public String Equalopportunitynation = "Nación con igualdad de oportunidades.";
    public String Backward = "Hacia atras.";
    public String Heresthekicker = "He aqui la parte ironica.";
    public String Nasty = "Asqueroso.";
    public String Bigoted = "Intolerante.";
    public String Misogynistic = "Misoginos.";
    public String Authoritariannationalists = "Nacionalistas autoritarios.";//60
    public String Imposingthesecrushingrules = "Imponiendo estas reglas aplastantes.";
    public String Thewokeleft = "El despertar se fue.";
    public String Side = "Lado.";
    public String Revered = "Venerado.";
    public String Upuntil = "Hasta.";
    public String Commited = "Comprometido.";
    public String Proof = "Prueba.";
    public String Dozens = "Docenas.";
    public String Overthelastfewyears = "En los ultimos años.";
    public String Nooses = "Sogas.";//70
    public String Nword = "Palabra para insultar a la gente de color.";
    public String Taunts = "Burlar.";
    public String Faked = "Falsificado.";
    public String Supply = "Suministro.";
    public String Against2 = "En contra de.";
    public String Rampant = "Desenfrenada.";
    public String Raceobsessed = "Obsesionado con la raza.";
    public String Unconscious = "Inconsciente.";
    public String Smallminded = "De mente pequeña.";
    public String Attorney = "Abogado.";//80
    public String Hadnothingtodo = "No tiene nada que ver.";
    public String Available = "Disponible.";
    public String Understand = "Entender.";
    public String Once = "Una vez.";
    public String Condescending = "Condescendiente.";
    public String Outright = "Total.";
    public String Expect = "Esperar.";
    public String Purely = "Puramente.";
    public String Basedon = "Basado en.";
    public String Merits = "Meritos.";//90
    public String Equitable = "Equtativo.";
    public String Hundred = "Cientos.";
    public String Realize = "Darse cuenta.";

    //Should Government Bail Out Big Banks?

    public String Financialsector =  "sector financiero";
    public String Governmentrescue =  "rescate gubernamental";
    public String Conventionalwisdom =  "sabiduría convencional";
    public String Shorttermpanic =  "pánico a corto plazo";
    public String Creditmarketfreeze =  "congelación del mercado de crédito";
    public String TroubledAssetReliefProgram =  "Programa de Alivio de Activos Problemáticos";
    public String PostDepressionbailout =  "rescate post-Depresión";
    public String Commercialbank =  "banco comercial";
    public String Globalbondholders =  "titulares globales de bonos";
    public String Shorttermcreditmarkets =  "mercados de crédito a corto plazo";
    public String Bondholders =  "titulares de bonos";
    public String Hedgefund =  "fondo de cobertura";
    public String Governmentsponsoredmortgagecompanies =  "empresas hipotecarias patrocinadas por el gobierno";
    public String Financialstorm =  "tormenta financiera";
    public String Globalmeltdown =  "colapso global";
    public String Governmentcontrol =  "control gubernamental";
    public String Financialinstitutions =  "instituciones financieras";
    public String Creditunderpins =  "el crédito respalda";
    public String Stockmarketcrash =  "colapso del mercado de valores";
    public String FederalReserve =  "Reserva Federal";
    public String Riskmodels =  "modelos de riesgo";
    public String Meltdown =  "colapso total";
    public String Deregulation =  "desregulación";
    public String Unmoored =  "sin anclaje";
    public String Dependent =  "dependiente";
    public String Enablingparent =  "padre permisivo";
    public String Bellyup =  "en bancarrota";
    public String Reckless =  "imprudente";
    public String Teetered =  "tambaleado";
    public String Whack =  "desorden";
    public String Lobbyists =  "grupos de presión";
    public String Policing =  "supervisión, regulación.";
    public String Depressions =  "Depresiones económicas, periodos prolongados de declive económico.";
}
