package com.leal.cipm_testing;

public class Defs {
    //hola alondra
    // fathers matter
    String between = "una preposición usada para " +
            "decir que algo esta entre dos cosas.";
    String children = "una palabra para referirse " +
            "a niños y niñas";
    String ago = "se usa con una expresión de tiempo " +
            "para indicar que algo fue en pasado," +
            "por ejemplo = years ago- años atras, ten " +
            "years ago- hace diez años ";
    String then = "entonces";
    String iasked = "yo pregunté";
    String which = "cual, usualmente la usamos cuando tenemos dos opciones";
    String poses = "presentar o constituir(un problema, peligro,dificultad)";
    String bigger = "mas grande(el sufijo ER se usa en " +
            "adjetivos cortos para hacer que comparen, " +
            "small/pequeño, smaller-mas pequeño," +
            " tall-alto,taller-mas alto)";
    String threat = "amenaza";
    String withouthmissingabeat = "esta es una exprecion coloquial, " +
            "es el equivalente en español a ¨sin titubear¨ ";
    String hesaid = "el dijo";
    String itwas = "fue";
    String who = "quien";
    String weall = "todos nosotros";
    String know = "saber o conocer";
    String that = "que (se usa para introducir una clausula)";
    String growup = "verbo compuesto, crecer";
    String likely = "propenso, probable";
    String poverty = "pobreza";
    String dropout = "salir de la escuela,dejar de ir a la escuela prematuramente";
    String endup = "terminar";
    String even = "incluso";
    String after = "después , después de, después de que";
    String controlling = "controlar, los verbos después " +
            "de cualquier preposición se escriben con terminación ing";
    String varying = "algo que varia";
    String householdincome = "ingreso del hogar";
    String jail = "la carcel";
    String mostlikely = "los mas probables/ superlativo ";
    String windup = "terminar, encontrarte a ti mismo en una situacion inesperada y no placentera";
    String eachother = "uno con el otro";
    String risen = "participio de elevar, elevado";
    String reached = "alcanzar en pasado, alcanzó";
    String during = "durante";
    String marriage = "matrimonio";
    String were = "eran o estaban ";
    String than = "que , se usa en contexto de comparacion";
    String raised = "criado, en este contexto raise se usa como <criar> ";
    String both = "ambos";
    String written = "escrito";
    String according = "según";
    String outofwedlock = "fuera de matrimonio";
    String birth = "nacimientos";
    String lessthan = "menos de ";
    String over = "sobre";
    String answer = "respuesta";
    String found = "Participio de find (encontrar) , encontrado";
    String law = "ley";
    String iff = "Conector condicional es el ´si´ en español,por ejemplo, si tu vienes yo voy";
    String subsidize = "subsidiar";
    String undesirable = "indeseable";
    String behavior = "comportamiento";
    String youwillget = "´will´ + get, juntos significan, tu obtendras. ´Will´ no tiene significado solo";

    String soCalled = "así llamado, se usa para mostrar que algo o alguien se designa comúnmente " +
            "por el nombre o término especificado";
    String war = "Guerra";
    String began = "comenzó";
    String begantoflatline = "comenzo alrededor";
    String from = "desde";
    String until = "hasta";
    String untilnow = "hasta ahora";
    String spent = "gastado, en esta situación esta justo después del has, has spent,ha gastado";
    String hasspent = "ha gastado";
    String tofightpoverty = "para luchar contra la pobreza";
    String rate = "calificar";
    String hasremainedunchanged = "se ha mantenido sin cambios";
    String haschanged = "ha cambiado";
    String dramatically = "dramáticamente";
    String Thatsbecause = "Eso es porque";
    String generous = "generoso";
    String ineffect = "en efecto";
    String abandon = "abandonar";
    String traditional = "tradicional";
    String financial = "financiero";
    String responsibilities = "responsabilidades";
    String suchdependency = "tal dependencia";
    String learnedhelplessness = "Desamparo aprendido";
    String disincentive = "desincentivo, especialmente una desventaja financiera, " +
            "que tiende a desalentar a las personas de hacer algo";
    String tryingtohelp = "Tratando de ayudar";
    String poor = "pobre";
    String nonpoor = "no pobre";
    String whether = "ya sea , expresar una duda o elección entre alternativas.";
    String additional = "adicionales";
    String respondents = "encuestados";
    String oncesaid = "una vez dijo";
    String headmitted = "él admitió";
    String runningwith = "juntarse con";
    String gangs = "pandillas";

    String structure = "estructura";
    String protection = "proteción";
    String calmyoudown = "cálmarte";
    String theway = "de la manera";
    String teachyou = "enseñarte";
    String howtobe = "a como ser";
    String myrough = "muy áspero o muy fuerte de caracter";
    String growingup = "creciendo";
    String fulltimejobs = "trabajos de tiempo completo";
    String asa = "como un";
    String janitor = "conserje";
    String also = "él también";
    String hismid80s = "alrededor de sus 80 años";
    String angry = "molesto";
    String bitter = "amargado";
    String insisted = "insistió";
    String racialsegregation = "segregacion racial";
    String yougetoutoflifewhatyouputintoit = "se refiere a = recibes lo que das";
    String blamingotherpeople = "culpar a otras personas";
    String whatcouldihavedonetochangetheoutcome = "que pude haber hecho yo para cambiar mi resultado";
    String Thisadviceshaped = "este consejo formo";
    String staffsergeant = "rango militar";
    String jimcrowsouth = "leyes que segregaban a las personas de raza negra de la sociedad";
    String fulltime = "de tiempo completo";
    String somehow = "de alguna manera";
    String cooked = "cocinaba";
    String andsomehowmanaged = "y de alguna manera logró";
    String nightschool = "escuela nocturna, una escuela que imparte clases por la noche, para " +
            "aquellos, generalmente adultos, que no pueden asistir durante el día";
    String gethisGED = "obtener su diploma de estudios generales";
    String heran = "que el administró";
    String thelaterapper = "el fallecido rapero";
    String fathersmatter = "los padres importan, o son importantes";
    String wehave = "en esta situación , el we have, no es nosotros tenemos, como está al lado del until-(hasta o hasta que), el we have se hace " +
            "subjuntivo y realmente dice *hasta que nosotros tengamos ";


    //Is America Racist??
    String Still = "todavía";
    String Certainly = "ciertamente";
    String Thinksso = "piensa de esta forma";
    String That = "que";
    String If = "sí, condicional";
    String Doesntthatmean = "eso no siginfica?";
    String So = "aquí el so se refiere a la acción anterior, “america ha cambiado y dramáticamente así";
    String Vote = "votar";
    String who2 = "quien";
    String was = "fue";
    String elected = "elegido";
    String almost = "casi";
    String later = "después";
    String thats = "eso es";
    String only = "solamente";
    String themost = "el mas , superlative , no hay nada por encima";
    String thereare = "hay , plural";
    String take = "toma";
    String marriage2 = "matrimonio";
    String wrote = "escribió";
    String viewed = "visto";
    String benchmark = "marcador";
    String stage = "escenario, en este caso se refiere al ultimo paso";
    String were2 = "eran, fueron, estaban";
    String until2 = "hasta";
    String Galluppoll = "poll es encuesta Gallup es una empresa que se dedica a hacer encuestas , una encuesta de Gallup.";
    String Found = "encontró";
    String That2 = "aquí este that se refiere a “ese numero “ no es “que” por que no esta introduciendo una clausula completa.";
    String Of = "de";
    String All = "todos";
    String By = "por";
    String Rising = "elevándose";
    String Whatabout = "expresión coloquial, como cuando tu dices “que hay sobre” o “que tal” y luego introduces una idea.";
    String Racialprofiling = "es una idea, perfil racial, se refiere a que la gente es detenida por la policía solo por su color de piel.";
    String Doesntthat = "eso no?";
    String Remains = "sigue siendo";
    String Summer = "Verano";
    String Became = "se convirtio";
    String Groundzero = "literal es donde sucedió un estallido atomico, pero se usa coloquialmente para indicar que fue el lugar que empezó un movimiento social."
            + "Shot- disparar en pasado";
    String Unarmed = "desarmado";
    String Teenager = "adolecente";
    String While = "mientras";
    String Cleared = "aquí se refiere a que “limpió” o “aclaró”";
    String Wrongdoing = "se refiere a cualquier hecho con malicia , error o crimen";
    String Citys = "aquí se refiere al “city´s pólice departmen” o el departamento de policía de la ciudad";
    String Bias = "favoritismo o sesgo";
    String Headlinegrabbingstat = "la primera palabra y sustantivo de esta frase es “stat” que es estadística headline es encabezado y grabbing viene de grab , ósea tomar con la mano, la frase completa es algo asi como la estadística que más agarro encabezados de periódico. A esto es a lo que le llamamos “noun adjective”";
    String Gap = "hueco";
    String Those = "aquellos";
    String Notsofast = "no tan rapido";
    String Coprise = "compone, contiene, esta compuesto por";
    String Account = "cuantan por";
    String Bigger = "mas grande";
    String Even = "incluso";
    String Than = "que";
    String Pd = "pólice department";
    String Cannot = "no puedes";
    String About = "acerca de";
    String Withouth = "sin";
    String Though = "aun que";
    String Commit = "cometer";
    String Almost = "casi";
    String Always = "siempre";
    String Accordingto = "según";
    String Bytheway = "por cierto";
    String Over = "en esta situación “over” se refiere a sobre o mas de";
    String Twice = "dos veces";
    String Thatmany = "esta es una frase cuando están juntas , es como decir de esos";
    String But = "pero";
    String Same = "mismo";
    String Mostly = "mayoritarimente";
    String Unlike = "no parecido a";
    String Dispatch = "parecido a “despachar” dispatch calls son cuando mandan a los policías aun lugar en especifico por una llamada de 911";
    String Whenitcomesto = "frase colloquial parecida a = “cuando tiene que ver con”";
    String Therefore = "por lo tanto";
    String Haveafieldday = "“tienen un dia de campo” frase coloquial o “se dan gusto”";
    String Actually = "realmente";
    String Published = "publico";
    String Called = "llamado";
    String Outof = "aquí se refiere a que tres de cada cuatro, no aplica aquí su significado literal de las palabras aisladas";
    String Drivers = "conductores";
    String Were = "fueron";
    String Average = "promedio";
    String Likely = "probables";
    String Speeding = "pasarse del limite de velocidad";
    String Seatbelt = "cinturón de seguridad";
    String Usage = "uso de";
    String Lower = "mas bajo";
    String Among = "entre";
    String From = "de";
    String Words = "palabras";
    String Becauseof = "cuando las palabras estas están juntas son -  a razón de, o por";
    String Also = "también";
    String Higher = "mas alto";
    String Rates = "tasa";
    String Whether = "ya sea";
    String Wearing = "usar, se usa para ropa, aquí se usa para el cinturón de seguridad";
    String Safety = "seguridad";
    String Thereis = "hay, singular";
    String Theleast = "el menos";
    String Better = "mejor";
    String Any = "cualquier";
    String Greater = "mas grande";

    //Don't Compare Yourself to Others

    String Doyoueverlook = "Alguna vez miras";
    String Iwish = "Yo deseo";
    String Everybody = "Todos";
    String Bet = "Apostar";
    String Compared = "Comparado (del verbo comparar)";
    String Yourself = "A ti mismo (Reflexivo)";
    String Do = "Palabra usada para poner énfasis al afirmar algo. Ejemplo = No necesito esto, pero SI necesito aquello.";
    String Own = "Propio";
    String Middle = "Mitad";
    String Asbigas = "Tan grande como";//10
    String Pretty = "Muy. También usado como bonito (a) en otros contextos.";
    String Hereswhy = "Aqua esta porque";
    String People = "Personas ( en plural)";
    String Whole = "Todo o completo";
    String Trick = "Truco";
    String HereswhatImean = "Aquí esta a lo que me refiero";
    String Happiness = "Felicidad";
    String Werebased = "Fuera basada";
    String Biggest = "el mas grande";//20
    String Business = "Negocio";
    String Idbemad = "Contraccion de I would. Yo estaría muy enojado";
    String Whoever = "Quien";
    String Hebeastme = "El me gana / El me vence";
    String Rich = "Rico";
    String Alot = "Mucho";
    String Like = "Como ( usado para comparación ). También puede significar gustar";
    String Therewere = "Hay ( En plural)";
    String Richer = "Mas rico";
    String Never = "Nunca";//30
    String Measure = "Medida";
    String Constitutes = "Constituye";
    String Success = "Exito";
    String Entertainment = "Entretenimiento";
    String Allthrough = "A traves";
    String Career = "Carrera ( universitaria )";
    String Customers = "Clientes";
    String Someday = "Algún dia";
    String Youllbe = "Contraccion de You will. Tu seras/estaras";
    String Successful = "Exitoso (a)";//40
    String Topguy = "hombre/chico superior";
    String Someone = "Alguien ";
    String Theyre = "Contraccion de They are. Ellos son/estaran";
    String Disease = "Enfermedad";
    String Save = "Salvar/Guardar ";
    String Justlike = "igual como, igual que";
    String Lawyer = "Abogado (a)";
    String Crazy = "Loco";
    String Makingaliving = "Expression = Literal indica hacer una vida, en otras palabras ganarse la vida";
    String Pursuing = "Del verbo Persue; Persiguiendo";//50
    String Findingmeaning = "encontrando significado";
    String What = "Usado como conector, lo que.";
    String First = "Primero";
    String Standup = "Standup de comedia o show de comedia";
    String Nobody = "Nadie";
    String Tunedoutcrowds = "Multitudes desconectadas, o multitudes que no ponen atención.";
    String Before = "Antes";
    String Jokes = "Chistes";
    String Laughing = "Del verbo Laugh. Riendo";
    String about = "Sobre de / Acerca de ";//60
    String Soldouthouses = "Houses es casas, aqui se refiere a lugares donde se hacen standups. Lugares agotados.";
    String Iwasntplaying = "Yo no estaba presentando. Play es usado como presentar. ";
    String Bigpayday = "Grandes dias de pago.";
    String Able = "Capaz";
    String Their = "Posesion = Su (de ellos/ellas)";
    String Dark = "Oscuro";
    String Struggle = "Luchas";
    String Envy = "Envidio";
    String Wentalongwithit = "que vienen con ello";
    String Factor = "Factorizas";//70
    String Sortof = "Tipo de";
    String Mixandmatchgame = "Es un juego donde mesa americano donde diferente fotos se juntan y se mezclan. El autor se refiere a esto para indicar como se agarra unas partes de una persona pero no lo otro, cuando se comparan.";
    String World = "Mundo";
    String Heresoneoflifeslittletruths = "Aquí hay una de las pequeñas verdades de la vida";
    String Packagedeal = "Paquete completo";
    String View = "Ver";
    String Someoneelseslife = "La vida de alguien mas ";
    String Cheating = "Trampa";
    String Prettycool = "Muy chido.";
    String Hangwithhim = "salir con el/ pasar el rato con el";//80
    String Pain = "Dolor";
    String Anybody = "Cualquiera";
    String Really = "Muy";
    String Awfulstuff = "Cosas terribles";
    String Dealwith = "lidiar con";
    String Battle = "batallar con";
    String Deadrockstars = "Estrellas de rock muertas";
    String Hard = "Dura";
    String Faceit = "enfrentalo";
    String Sellout = "Agotar";//90
    String Biggestvenues = "lugares mas grandes (venues se refiere al lugar donde el se presenta)";
    String PrimetimeTVshow = "Programa de televisión en horario de máxima audiencia";
    String Viewers = "Espectadores";
    String Half = "Mitad";
    String Myself = "Mi mismo (a)";
    String Imdoingokay = "Expression = Estoy bien, me esta yendo bien";
    String Try = "Intentar";

    //Fix Yourself
    String Blamingothers = "Culpando otros ( Blame = Culpar)";
    String Wasteoftime = "Perdida de tiempo";
    String That3 = "Eso";
    String Learn = "Aprender";
    String Anything = "Cualquier cosa";
    String Grow = "Crecer";
    String Mature = "Madurar";
    String Thus = "Por lo tanto";
    String Life = "Vida";
    String Better1 = "Mejor";//10
    String As = "Como (Usado para comparar = como profesor)";
    String Thereare = "Hay";
    String Attitudes = "Actitudes";
    String Toward = "Hacia";
    String Sorrows = "Penas";
    String Those1 = "Aquellos";
    String First1 = "Primer/ Primero (a)";
    String World1 = "Mundo";
    String Second = "Segundo";
    String Differently = "Diferentemente";//20
    String Couple = "Pareja";
    String Onthebrink = "A punto / al borde";
    String Theyre1 = "Contraccion = They are, Ellos son/estan";
    String Hurt = "Heridos (as)";
    String Angry = "Molestos (as) / Enojados (as)";
    String Unhappy = "Infeliz";
    String Bitter = "Amargado";
    String Husband = "Esposo";
    String Recalls = "Recuerda";
    String Things = "Cosas";//30
    String Wife = "Esposa";
    String Reasons = "Razones";
    String Nolongerlivewithher = "Ya no puede vivir con ella";
    String Harried = "Acosada (o)";
    String Disillusioned = "Desilusionada";
    String All1 = "Todas (os)";
    String Ways = "Maneras";
    String Letherdown = "La decepciono";
    String Each = "Cada quien";
    String Changes = "Cambios";//40
    String Prospects = "Prospectos";
    String Grim = "Oscuro";
    String Arent = "Contraccion = Are not, no son/estan";
    String Youre = "Contraccion = You are, tu estas/eres";
    String Cant = "Contraccion = Can not, no puedes (no poder)";
    String Yourself1 = "Tu mismo";
    String Courage = "Coraje, Valor";
    String Easier = "Mas facil";
    String Muchmore = "Mucho mas";
    String Gratifying = "Gratificante";//50
    String Basest = "Mas bajos";
    String Desires = "Deseos";
    String Someoneelse = "Alguien mas";
    String Youthful = "Juvenil";
    String Makingastatement = "Haciendo una declaración";
    String Against = "En contra";
    String Smashing = "Aplastando / Del verbo Smash";
    String Storefront = "Fachada";
    String Business1 = "Negocio";
    String Otherthan = "Aparte de";//60
    String Bring = "Traer";
    String Harm = "Daño";
    String Whohavenothingtodo = "Quien no tienen nada que ver";
    String Guilt = "Culpa";
    String Doubt = "Duda / incertidumbre";
    String Shame = "Lastima";
    String Inevitably = "Inevitablemente";
    String Suppressed = "Suprimido (a)";
    String Beliefs = "Creencias";
    String Unchanged = "Sin alterar/cambiar";//70
    String Foster = "Fomentar";
    String Anger = "Enojo";
    String Alienation = "Alienación";
    String Play = "Obra (También usado como jugar en otros contextos)";
    String Characters = "Personajes";
    String Veryhardtime = "Tiempo muy didicil";
    String Profound = "Profundo (a)";
    String Unhappiness = "Infelicidad";
    String Suffering = "Sufrimiento";
    String Own1 = "Propia (o)";//80
    String Fault = "Culpa";
    String Takenaback = "Expression = Tomado(a)  por sorpresa";
    String If1 = "Si (Condicional = Usados para expresar que algo depende de algo mas)";
    String Herfault = "Su culpa (Her = indicando posesión de ella, su de ella)";
    String Shes = "Contraccion = She is, Ella es/esta";
    String Doomed = "Condenada (o)";
    String Herself = "Ella misma";
    String Seem = "Parecen";
    String Consigned = "Consigando (a)";
    String Fate = "Destino";//90
    String Mostofus = "Mayoría de nosotros (as)";
    String Chance = "Oportunidad";
    String Questions = "Preguntas";
    String Full = "Completa (o)";
    String Advantage = "Ventaja";
    String Answer = "Respuesta";
    String Try1 = "Intenta (del verbo intentar)";
    String Stopdoing = "Deja de hacer";
    String Wrong = "Equivocado (a)";
    String Waste = "Gastes / Pierdas";//100
    String Inopportunequestioning  = "cuestionamiento inoportuno (a)";
    String Without = "Sin";
    String Enlightening = "Literal es aluzar, pero se refiere a darle luz a algo para que se entienda mejor";
    String Deflect = "Desviar";
    String Something = "Algo";
    String Right = "Bueno ( Esta palabra tiene varios usos, pero indica bueno)";
    String Payingattention = "Poner atención (Literal es pagar atención pero en español es poner atención.)";
    String Showuplate = "Llegar tarde";
    String Spend = "Gastar";
    String Itsnotamatter = "No es un asunto/cuestion";//110
    String Some = "Algunos/Algunas";
    String Imposed = "Impuesta (o)";
    String Whatcouldyouputright = "Literal es que podrías poner derecho/bien pero se refiere a ¿Que podrías arreglar?";
    String Rightnow = "Ahora mismo";
    String Gettoworkontime = "Llega a tiempo al trabajo, get to es usado como llegar";
    String Diligently = "Diligentemente";
    String Utilize = "Utilizar";
    String Peaceful = "Tranquilo (a)";
    String Productive = "Productivo";
    String Desirable = "Deseable";//120
    String Weeks = "Semanas";
    String Months = "Meses";
    String Attentive = "Atento (a)";
    String Effort = "Esfuerzo";
    String Yourmindwillclear = "Tu mente se aclarará";
    String Less = "Menos";
    String Path = "Camino";
    String Infront = "Enfrente";
    String Willshine = "Verbo shine es brillar, con will enfrente indica futuro, brillará";
    String Brightly = "brillantemente";//130
    String Gettingyourownway = "meterte en tu propio camino";
    String Instead = "En lugar de";
    String Troubletoyourself = "problemas a ti mismo";
    String Society = "Sociedad";
    String Suffer = "Sufrir";
    String Thatsthepriceofbeingalive = "Ese es el precio de estar vivo";
    String Maybe = "Alomejor";
    String Enough = "Suficiente";
    String Burden = "Carga";
    String Inthatfashion = "Es un expression indicando = de esa manera";//140
    String Nobly = "Noble";
    String Purpose = "Proposito";
    String Properway = "Forma/manera apropiada";
    String Fix = "Arregla";
    String Inthatmanner = "de esa manera";
    String Atleast = "Al menos";
    String Place = "Lugar";

    String Delusion = "creencia que contradice la realidad";
    String Discerning = "Perspicaz, exigente, selectivo";
    String Supervisedcurfews = "toque de queda supervisado.";
    String Intimate = "intimo/a.";
    String Violated = "violado/a (en el sentido de haber sido objeto de una acción no deseada o no consentida).";
    String Vulnerable = "vulnerable, frágil.";
    String Confined = "limitado/a, restringido/a.";
    String Satisfying = "satisfactorio/a, gratificante.";
    String Emotionally = "emocionalmente.";
    String Psychologically = "psicológicamente.";
    String Physically = "físicamente.";
    String Spiritually = "espiritualmente.";
    String Commonsense = "sentido común.";
    String Agenda = "programa, plan, intención.";
    String Sociology = "sociología.";
    String Anthropology = "antropología.";
    String Genderstudies = "estudios de género.";
    String Spectrum = "espectro.";
    String Internalfeelings = "sentimientos internos.";
    String Toytrucks = "camiones de juguete.";
    String Pinkandbluestereotype = "estereotipo de rosa y azul.";
    String Reality = "realidad.";
    String Collegeentertainment = "entretenimiento universitario.";
    String Makingstuffup = "inventando cosas.";
    String Pushinganagenda = "promoviendo una agenda.";
    String Traditionally = "tradicionalmente.";
    String Marriage = "matrimonio.";
    String Experience = "experiencia.";
    String Research = "investigación.";
    String Associateprofessor = "profesor asociado.";
    String Theology = "teología.";
    String Philosophy = "filosofía.";
    String Beachball = "pelota de playa.";
    String Distinctnature = "naturaleza distinta.";
    String Bodyparts = "partes del cuerpo.";
    String Biology = "biología.";
    String Hormones = "hormonas.";
    String Expressemotions = "expresar emociones.";
    String Needs = "necesidades.";
    String Desires2 = "deseos.";
    String Uninvitedtouch = "toque no deseado.";
    String Leg = "pierna.";
    String HollywoodReporter = "Reportero de Hollywood.";
    String CoStar = "coprotagonista.";
    String Actingout = "representando.";
    String Commonsense2 = "sentido común.";
    String Rememberthebeachball = "recuerda la pelota de playa.";

    //Don't Waste Your Time
    String Date = "Tener citas.";
    String Purpose2 = "Proposito.";
    String Getmarried = "Casarse.";
    String Toofast = "Muy rapido.";
    String Uncomfortable = "Incomodo.";
    String Hookup = "Iniciar una relación romántica o sexual con alguien.";
    String Casualflings = "Iventuras casuales.";
    String Havefun = "Divertirse.";
    String Dontgetmewrong = "No me malinterpretes.";
    String Deeper = "Mas profundo.";//10
    String Happiness2 = "Felicidad.";
    String Certainly2 = "Ciertamente.";
    String Marriage2 = "Matrimonio.";
    String Topic = "Tema.";
    String Atleast2 = "Al menos, por lo menos.";
    String Else = "Más.";
    String Letsfaceit = "Seamos realistas / Encaremoslo.";
    String Asfasasitgoes = "Hasta donde llegue.";
    String Frankly = "Francamente.";
    String Smart = "Inteligente.";//20
    String Playout = "Reproducir.";
    String Often = "Seguido.";
    String Relationship = "Relacion.";
    String Commitment = "Compromiso.";
    String Infact = "De hecho.";
    String Arise = "Surgir.";
    String Whim = "Capricho.";
    String Develop = "Desarrollar.";
    String Tryout = "Prueba.";
    String Less2 = "Menos.";//30
    String Lack = "Falta de.";
    String Afford = "Poder pagar.";
    String Enterprise = "Empresa.";
    String Entirely = "En su totalidad / Totalmente.";
    String Build = "Construir.";
    String Shared = "Compartido.";
    String Beliefs2 = "Creencias.";
    String Partner = "Pareja / Compañero.";
    String Profound2 = "Profundo.";
    String Understandings = "Entendimientos.";//40
    String Cutcome = "Resultados.";
    String Fool = "Engañar.";
    String Thrilled = "Emocionarse.";
    String Kombucha = "Bebida alcholica.";
    String Getdownto = "Llegar a.";
    String Overthelongrun = "A largo plazo.";
    String Stuff = "Cosas.";
    String Faith = "Fe.";
    String Sooner = "Mas pronto.";
    String Doubt2 = "Duda.";//50
    String Stuck = "Atrapado.";
    String Deadendrelationships = "Relaciones sin salida.";
    String Articulate = "Articular / Expresar.";
    String Crave = "Anhelar.";
    String Healthier = "Mas sano.";
    String Wealthier = "Mas rico.";
    String Towards = "Hacia.";
    String Wasteoftime2 = "Perdida de tiempo.";
    String Between = "Entre.";
    String Taketheplunge = "Que ha dado el paso / Que se ha casado.";//60
    String Country = "País.";
    String Citizen = "Ciudadano.";
    String Thelatter = "El ultimo.";
    String Expectations = "Expectativas.";
    String Mean = "Significar.";
    String Reluctant = "Reacios.";
    String Sign = "Firmar.";
    String Ruleofthumb = "Una regla no escrita que todos seguimos.";
    String Thekindof = "El tipo de.";
    String Career2 = "Carrera.";//70
    String Getitright = "Hacerlo bien.";
}
